# Generated by Django 4.2 on 2023-05-01 23:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('LTtApp', '0005_tour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='image',
            new_name='imagen',
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='title',
            new_name='titulo',
        ),
        migrations.AddField(
            model_name='tour',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='tour_audio/'),
        ),
        migrations.AddField(
            model_name='tour',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tour',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Paso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=255)),
                ('imagen', models.ImageField(blank=True, upload_to='pasos/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='paso_audio/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LTtApp.tour')),
            ],
        ),
    ]
