# Generated by Django 4.2 on 2023-05-01 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LTtApp', '0006_rename_description_tour_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paso',
            name='titulo',
        ),
    ]
