# Generated by Django 4.2 on 2023-05-02 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LTtApp', '0007_remove_paso_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='paso',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='paso',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='tour',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='tour',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='paso',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='pasos/'),
        ),
    ]
