# Generated by Django 4.2 on 2023-05-02 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LTtApp', '0008_paso_latitude_paso_longitude_tour_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='tipo_de_tour',
            field=models.CharField(choices=[('naturaleza', 'Naturaleza'), ('cultural', 'Cultural'), ('ocio', 'Ocio')], default='naturaleza', max_length=10),
        ),
    ]
