# Generated by Django 4.2 on 2023-05-02 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LTtApp', '0009_tour_tipo_de_tour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='tipo_de_tour',
            field=models.CharField(blank=True, choices=[('naturaleza', 'Naturaleza'), ('cultural', 'Cultural'), ('ocio', 'Ocio')], default=None, max_length=10, null=True),
        ),
    ]
