# Generated by Django 4.2 on 2023-05-07 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LTtApp', '0010_alter_tour_tipo_de_tour'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='duracion',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='recorrido',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
