# Generated by Django 4.2 on 2023-05-07 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LTtApp', '0011_tour_duracion_tour_recorrido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='duracion',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Duración en minutos'),
        ),
    ]
