# Generated by Django 4.2.2 on 2023-06-30 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LTtApp', '0012_alter_tour_duracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='duracion',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Duración en minutos'),
        ),
    ]
