# Generated by Django 4.2 on 2023-07-23 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LTtApp', '0013_alter_tour_duracion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paso',
            options={'ordering': ['created_at']},
        ),
    ]
