# Generated by Django 4.2 on 2023-07-23 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LTtApp', '0014_alter_paso_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paso',
            options={'ordering': ['step_number']},
        ),
        migrations.AddField(
            model_name='paso',
            name='step_number',
            field=models.IntegerField(default=0),
        ),
    ]
