# Generated by Django 4.2 on 2023-11-11 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LTtApp', '0015_alter_paso_options_paso_step_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='paso',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
