# Generated by Django 4.2 on 2023-11-11 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LTtApp', '0016_paso_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paso',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paso',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paso',
            name='step_number',
            field=models.IntegerField(default=None),
        ),
    ]
