# Generated by Django 4.2 on 2023-12-12 01:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LTtApp', '0017_alter_paso_latitude_alter_paso_longitude_and_more'),
    ]

    operations = [

        migrations.AlterField(
            model_name='tour',
            name='tipo_de_tour',
            field=models.CharField(blank=True, choices=[('nature', 'Naturaleza'), ('cultural', 'Cultural'), ('leisure', 'Ocio')], default=None, max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='TourRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LTtApp.tour')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
