# Generated by Django 4.2 on 2023-12-12 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LTtApp', '0018_rename_imagen_paso_image_alter_tour_tipo_de_tour_and_more'),
    ]

    operations = [

        migrations.AddField(
            model_name='paso',
            name='tittle',
            field=models.TextField(blank=True, null=True),
        ),
    ]
