# Generated by Django 4.2 on 2024-02-19 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LTtApp', '0020_encuesta_rename_imagen_paso_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='acceso_a_tours',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='ayuda_a_lograr_objetivos',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='duracion_optima',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='edad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='flexibilidad_de_horarios_idioma',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='formato_red_social',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='genero',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='precio_dispuesto_a_pagar',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='probabilidad_de_volver_a_realizar_tour',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='recomendar_producto',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='tours_al_anio',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='usar_producto_en_proximas_vacaciones',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='valoracion_contenido',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='valoracion_duracion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='valoracion_formato',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='valoracion_tour',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='viajes_al_anio',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
