# Generated by Django 5.0.2 on 2024-03-24 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LTtApp', '0021_alter_encuesta_acceso_a_tours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuesta',
            name='otro_acceso',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
