# Generated by Django 5.0.2 on 2024-03-24 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LTtApp', '0022_encuesta_otro_acceso'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuesta',
            name='otro_nacionalidad',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
