# Generated by Django 5.0 on 2024-04-03 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LTtApp', '0023_encuesta_otro_nacionalidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuesta',
            name='id_tour',
            field=models.TextField(blank=True, null=True),
        ),
    ]
