# Generated by Django 4.2.5 on 2024-05-31 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LTtApp', '0025_valoracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='idioma',
            field=models.CharField(default='es', max_length=2),
        ),
        migrations.AddField(
            model_name='tour',
            name='validado',
            field=models.BooleanField(default=False),
        )       
    ]
