# Generated by Django 4.2.5 on 2024-05-31 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LTtApp', '0026_tour_idioma_tour_validado_tourrelation'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_en', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tour_en', to='LTtApp.tour')),
                ('tour_es', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tour_es', to='LTtApp.tour')),
            ],
        ),
    ]
