# Generated by Django 5.0.2 on 2024-07-07 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LTtApp', '0027_tourrelation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paso',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='pasos/'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='imagen',
            field=models.ImageField(max_length=255, upload_to='tours/'),
        ),
    ]
