# Generated by Django 4.2.5 on 2024-07-30 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LTtApp', '0027_tourrelation'),
        ('LTtApp', '0029_create_initial_groups'),
    ]

    operations = [
    ]
