# Generated by Django 4.2.5 on 2024-08-03 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LTtApp', '0028_alter_paso_image_alter_tour_imagen'),
        ('LTtApp', '0030_merge_0027_tourrelation_0029_create_initial_groups'),
    ]

    operations = [
    ]
