# Generated by Django 4.2.5 on 2024-08-06 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LTtApp', '0032_customuser_rol_customuser_username_tour_original_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='suma_valoraciones',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tour',
            name='total_valoraciones',
            field=models.IntegerField(default=0),
        ),
    ]
